### PR TITLE
Update BasePath.php

### PR DESCRIPTION
**Pull request by mav2287**
This would store the original URI in an attribute and allow for custom naming of the attribute.

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi, @mav2287 
Thanks for your contribution. It looks a good idea, but I'd make it optional, and disabled by default to keep backward compatibility and ensure that existing attributes are not overriden.

So I propose that `$this->attribute` is `null` by default and only after configure it the original basepath is saved.

Btw, maybe we should save only the uri path, not the entire uri object.

**Comment by mav2287** [comment]
Having it off by default makes sense to me. In terms of the whole URI the only reason I did that was to just keep the changes minimal. What are thinking in terms of the adjustments?

**Comment by oscarotero** [comment]
I think that if this middleware changes only the path, it should save only the path in the attribute. The full url contains much more information that is not relevant (and even it could be changed by other middlewares, like the domain, protocol, etc).

Note that the original path can be recovered from `$_SERVER['REQUEST_URI']` (in psr7 it's `$request->getServerParams()['REQUEST_URI']`), so maybe this feature makes no sense in most cases.

**Comment by mav2287** [comment]
I had a similar thought, however I think putting the original path in an attribute is a bit cleaner and in my opinion may be easier to work with and have useful to have. If you are dealing with query params and use REQUEST_URI you have to parse off the query params ( trivial I know ), but an extra step none the less.

**Pull request closed without merging**
